import type { Metadata } from "next";

import Navbar from "./components/(navbar)/Navbar";
import Footer from "./components/(footer)/Footer";

export const metadata: Metadata = {
  title: "INVOICERY",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <>
      <Navbar />
      <main>{children}</main>
      <Footer />
    </>
  );
}
